services:
  mysql:
    image: mysql:8.0
    container_name: bd_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: produtos
      MYSQL_USER: user
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql