services:
  mysql:
    image: mysql:8.0
    container_name: bd_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: produtos
      MYSQL_USER: user
      MYSQL_PASSWORD: senha123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  api:
    image: desafio-crud-api
    container_name: desafio-crud-api
    restart: always
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://user:senha123@mysql:3306/produtos
    env_file:
      - .env
    depends_on:
      - mysql
  